name: pose_selfie_app
description: A Flutter application for pose selfie.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  get: ^4.6.6
  # Network
  http: 0.13.6
  # Storage
  shared_preferences: ^2.2.0
  # Cache
  cached_network_image: ^3.2.3
  # UI
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  # Camera & Media
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  video_player: ^2.8.2
  chewie: ^1.7.4
  # Permission
  permission_handler: ^11.2.0
  # Image Processing
  image: ^4.1.3
  path_provider: ^2.1.2
  torch_light: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: BowlbyOne
      fonts:
        - asset: assets/fonts/BowlbyOne-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf

# flutter_native_splash:
#   color: "#000000"
#   android: true
#   ios: true
#   web: false
# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo_app.png"
  
